### ISSUE TITLE
stole my css

### ISSUE THREAD

**Issue by EddieTheEd** [Grim4Reaper/Year11Notes#3]
**Describe the bug**
The css is literally ctrl c ctrl v from my repo

**To Reproduce**
1. Open webpage
2. See index page
3. "hmm, oddly similar to eds"
4. Open notice board (on my website)
5. Is literally the same

**Expected behavior**
An ounce of originality

**Screenshots**
![image](https://user-images.githubusercontent.com/103193479/229034967-2abd721a-dbb3-4fb6-bbd5-490fc46c94e6.png)
![image](https://user-images.githubusercontent.com/103193479/229035015-28dfe69d-753b-4412-a4c3-9a36894f243c.png)

**Desktop (please complete the following information):**
 - Device: Computer
 - OS: Linux
 - Browser: Thorium

**Additional context**
There are also serious slanderous statements on the index page. I am sure these were placed accidentally, and invite Tag to remove them posthaste.

**Comment by Grim4Reaper** [comment]
The css is yours at the moment because I am trying to do custom css per page
